POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "puszek",
   "email": "kotekpsotek@gmail.com",
   "password": "puszek123"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "mati",
   "email": "mati@gmail.com",
   "password": "mati123"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "test",
   "email": "test@test.com",
   "password": "test123"
}