POST http://localhost:3001/api/candidates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB1c3playIsImlkIjoiNjUyMTQwOWJlM2RmZDYzYjI4MGQzYTgxIiwiaWF0IjoxNjk2NjgxNDY5fQ.QZY5ys674hgiwFd9A1qG40lRQte9w_2ydbssUfTwy1o


{
      "firstName": "qqqqqqq",
      "lastName": "baqqqqqqti",
      "phone": "423232322123",
      "email": "cheqqqqqck@gmail.com",
      "location": "Przewowwrsk",
      "firstContact": "2023-05-12",
      "skill": "JavaScript",
      "seniority": "Junior"
}